### ISSUE TITLE
[Issue] ERROR: Failed to produce message (12922 bytes): Local: Unknown Topic

### ISSUE THREAD

**Issue by J0nnyDisk0** [OTRF/mordor#24]
Howdy,

HELK is healthy and workin but never used mordor until today, this is the error while trying to:

kafkacat -b $HELK_IP:9092 -t winlogbeat -P -l empire_dcsync_2019-03-01174830.json 

as from https://mordor.readthedocs.io/en/latest/import_mordor.html

**Comment by Cyb3rWard0g** [comment]
Hey @J0nnyDisk0 , Thank you for giving Mordor a try :) what is the error you are getting?

**Comment by J0nnyDisk0** [comment]
I am getting:
RROR: Failed to produce message (12922 bytes): Local: Unknown Topic

(the bytes change with each attempt). Thanks for the quick reply!

**Comment by Cyb3rWard0g** [comment]
So the topic `winlogbeat` doesnt exist then? Can you run the following:

`kafkacat -L -b $HELK_IP:9092`

**Comment by Cyb3rWard0g** [comment]
oh and btw this is the link for the docs: https://mordordatasets.com/import_mordor.html

**Comment by J0nnyDisk0** [comment]
That's the doc I was working with. On the command you told me to do I got the following:
Failed to Aquire Metadata: Local: Timed Out

i might rebuild from the ground up could have been something I did.

**Comment by xiaodupi-zyq** [comment]
Have you solved

**Comment by Cyb3rWard0g** [comment]
Hey @xiaodupi-zyq , are you having the same issue ingesting to HELK? Let me know I can try to replicate it.

**Comment by xiaodupi-zyq** [comment]
> Hey @xiaodupi-zyq , are you having the same issue ingesting to HELK? Let me know I can try to replicate it.

yes，I have the same issue

**Comment by Cyb3rWard0g** [comment]
ok. Can you provide the name of the dataset you are trying to ingest? Is it the same DCSync?? Thank you!

**Comment by xiaodupi-zyq** [comment]
> ok. Can you provide the name of the dataset you are trying to ingest? Is it the same DCSync?? Thank you!

apt29_evals_day1_manual_2020-05-01225525.json

**Comment by MikzTwix** [comment]
having the same trouble is this fix? may you please share thank you.

**Comment by Cyb3rWard0g** [comment]
Working on it.

**Comment by MikzTwix** [comment]
> Working on it.

Thank you for your hard work.

**Comment by Cyb3rWard0g** [comment]
@MikzTwix I get the same decompressing issue you are having. I will have to record it again. I do not know what happened. there. However, this issue is regarding the Kafka topic.

```wardog@UBUNTU5:~$ tar -xzvf empire_dcsync.tar.gz
empire_dcsync_2019-03-01174830.json

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
wardog@UBUNTU5:~$ ls
HELK  empire_dcsync.tar.gz  empire_dcsync_2019-03-01174830.json 
```
I simply deploy an Ubuntu Box in Azure (fresh 18)

Install Kafkacat

```
apt install kafkacat
```

Send data
```
kafkacat -b localhost:9092 -t winlogbeat -P - l empire_dcsync.json
```

Then I access the Elasticsearch docker container
```
sudo docker exec -ti helk-elasticsearch bash
```

then I run the following command to check my indices and the amount of record. Remember this is a fresh HELK install with no data being sent from endpoints

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/9653181/92194887-b24a9400-ee39-11ea-8ec7-46d5b90bc4c5.png">

**Comment by Cyb3rWard0g** [comment]
Then I ran a similar query to the one in the docs and I got results. I had to set my time to 2 years

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/9653181/92195933-166e5780-ee3c-11ea-937c-98d9070f17bb.png">

**Comment by Cyb3rWard0g** [comment]
I cannot replicate the pipeline issue.

**Comment by MikzTwix** [comment]
Thanks @Cyb3rWard0g I'll try it later this day thank you again for your work.

**Comment by MikzTwix** [comment]
Thanks a lot I got it working this time.

I use APT29 Datasets and its working perfectly.

<img width="1132" alt="Discover - Kibana 2020-09-04 23-21-56" src="https://user-images.githubusercontent.com/28039368/92255954-9d3b3700-ef05-11ea-87ca-1c567c7f670d.png">

![elasticsearch — ssh spladmin@192 168 175 131 — 110×24 2020-09-04 23-22-09](https://user-images.githubusercontent.com/28039368/92255971-a4624500-ef05-11ea-83a8-c1f90e03318c.png)

**Comment by driesbuyck** [comment]
@MikzTwix, @Cyb3rWard0g  The weird thing is that it is going to the indexme index while it should go to the log-* indexes.
I have the same problem when I try to import mordor datasets. I tried to have a look but I'm struggling how I can get decent troubleshooting logs for logstash. I can see it hits the default indexme via 9998-catch_all-output.conf.

**Comment by Cyb3rWard0g** [comment]
Hello @driesbuyck , that should be a question for HELK project. I also believe that if you send it to winevent topic https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/0002-kafka-input.conf#L9 , that should work. I will close this issue since it was related to the other question about APT29 dataset. Thank you all!
