### ISSUE TITLE
An Error Occured while loading the archive

### ISSUE THREAD

**Issue by MikzTwix** [OTRF/mordor#32]
Ola 

I encounter some error on the data sets while extracting the content each.

I try to extract Empire DCsync for testing but failed to extract

Please see the screen shot of the error.

![Screen Shot 2020-09-02 at 10 56 09 PM](https://user-images.githubusercontent.com/28039368/92000250-e6598280-ed6f-11ea-8d49-4fc995051b82.png)

But the other files like the Day1 of APT29 is extractable.

**Comment by Cyb3rWard0g** [comment]
Hey @MikzTwix , can you share the link for the dataset and how you are trying to decompress it?

**Comment by MikzTwix** [comment]
to be exact the empire_dcsync on the defense evasion folder.

I tried it right now and it seems working no error receive decompressing the tar gz file.

**Comment by Cyb3rWard0g** [comment]
ahh niceee! ok thank you checking again. if it works now, then I will close this issue. i believe you have an issue to import it to HELK right?
