### ISSUE TITLE
% ERROR: Failed to produce message (11500 bytes): Local: Unknown topic

### ISSUE THREAD

**Issue by sec-balkan** [OTRF/mordor#41]
Estoy siguiendo el tutorial (https://mordordatasets.com/consume/kafka.html) pero a la hora de meter los .json en Elastic a través de kafkacat no funciona.

_I'm following the tutorial (https://mordordatasets.com/consume/kafka.html) but when it comes to put the .json in Elastic through kafkaca it doesn't work._

root@ubuntu:/tmp/kafkacat# ./kafkacat -b ip:9092 -t winlogbeat -P -l empire_dcsync_dcerpc_drsuapi_DsGetNCChanges_2020-09-21185829.json

% ERROR: Failed to produce message (11500 bytes): Local: Unknown topic

root@ubuntu:/tmp/kafkacat# ./kafkacat -L -b ip:9092

% ERROR: Failed to acquire metadata: Local: Timed out

**Comment by Cyb3rWard0g** [comment]
Hello @sec-balkan ! the topic does not exist looks like and is Kafka running?

**Comment by sec-balkan** [comment]
Solved! Thanks.
